// client/src/pages/Chat.tsx
import { FormEvent, useCallback, useEffect, useRef, useState } from 'react'

const Chat = () => {
    const socketRef = useRef(new WebSocket("ws://localhost:8080/chat"))
    const [massage, setMassage] = useState("");


    const handelSend = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        if (massage) {
            console.log("I am Sending Stuff")
            const payload = JSON.stringify({ type: 'chat message', massage })
            socketRef.current.send(payload);
            setMassage('');
        }
        else console.log(" I Dose Not Do anyThing")
    }

    const handler = useCallback((x: MessageEvent<unknown>) => {
        console.log(x)
    }, [])

    useEffect(() => {
        socketRef.current.addEventListener("message", handler);
        return () => {
            // eslint-disable-next-line react-hooks/exhaustive-deps
            socketRef.current.removeEventListener("message", handler)
        }
    }, [handler])

    return (
        <main>
            <form onSubmit={(e) => handelSend(e)} className="flex flex-col gap-2">
                <label htmlFor="send-massage-input">Send Massage</label>
                <input type="text" id="send-massage-input" value={massage} onChange={(e) => setMassage(e.target.value)} placeholder="..." />
                <button type="submit">Send</button>
            </form>
        </main>
    )
}

export default Chat

// client/src/pages/Chat.vue
<script setup lang="ts">
import * as socketIo from 'socket.io-client'

const socket = socketIo.connect("ws://localhost:9090")
let massage = ""


const handelSend = (e: Event) => {
  e.preventDefault();
    if (massage) {
      console.log("I am Sending Stuff")
      socket.emit('chat message', massage);
      massage = '';
    }
    console.log(" I Dose Not Do anyThing")
}

socket.on('chat message', (msg) => {
  console.log("Massage from server ", msg)
  });

</script>

<template>

<main>
  <form v-on:submit="handelSend" class="flex flex-col gap-2">
    <label for="send-massage-input">Send Massage</label>
    <input type="text" id="send-massage-input" v-model="massage" placeholder="...">
    <button type="submit">Send</button>
  </form>
</main>

</template>

<style scoped>

</style>
